version: "3.5"
services:
  server:
    build:
      context: .
      dockerfile: ./server.Dockerfile
      args:
        ENV: development
    container_name: server
    env_file:
      - app/trading/.env.server
    depends_on:
      - trading-db
    ports:
      - 8080:8080
    volumes:
      - ./app/trading:/trading/app/trading
      - ./lib/trading-db:/trading/lib/trading-db
      - ./lib/trading-strategy:/trading/lib/trading-strategy
    command: >
      uvicorn app:app --host 0.0.0.0 --port 8080 --reload
    networks:
      - default
  server-test:
    build:
      context: .
      dockerfile: ./server.Dockerfile
      args:
        ENV: test
    container_name: server-test
    env_file:
      - app/trading/.env.test
    depends_on:
      - trading-db
    volumes:
      - ./app/trading:/trading/app/trading
      - ./lib/trading-db:/trading/lib/trading-db
      - ./lib/trading-strategy:/trading/lib/trading-strategy
    command: >
      pytest tests
    networks:
      - default
  trading-db:
    image: postgres:14
    container_name: trading-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=trading
    ports:
      - 5432:5432
    volumes:
      - "./tools/infra/trading-db/data:/var/lib/postgresql"
    networks:
      - default
