version: "3.5"
services:
  trading-db:
    image: mysql:8.0
    container_name: trading-db
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_ROOT_HOST=%
      - MYSQL_HOST=127.0.0.1
      - MYSQL_DATABASE=trading
    ports:
      - 33061:3306
    volumes:
      - "./tools/infra/trading-db/data:/var/lib/mysql"
