version: "3.5"
services:
  trading-db:
    image: postgres:14
    container_name: trading-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=trading
    ports:
      - 54321:5432
    volumes:
      - "./tools/infra/trading-db/data:/var/lib/postgresql"
